name: ChatTags
version: ${project.version}
main: com.abderrahimlach.TagPlugin
author: AbderrahimLach
description: Create your own creative tags with a cool UI and much more!
softdepend: [PlaceholderAPI]