# Storage methods:
# - MySQL (3306)
# - MongoDB (27017)
storage-method: mysql

# You can specify a port if differs
storage:
  host: 'localhost'
  username: 'root'
  password: 'password'
  database: 'chattags'

  # Sets the size of MySQL Connection pool
  # More information can be found here:
  # - https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  maximum-pool-size: 10

# The way the tag should be displayed in chat
tag-format:
  enabled: true
  format: "{tag} <%1$s> %2$s"